import { styled } from '../stitches.config';
import { Header } from '../components/Header'
import Head from 'next/head';
import { FooterColumns } from '../components/Footer';
import { HowToHelp } from '../components/HowToHelp';

const HeaderContainer = styled('div', {
  // TODO: use an stitches util for this repeated style or better, create a component called "HeaderContainer" just with this HeaderContainer style logic
  boxShadow: '0px 4px 4px rgba(0, 0, 0, 0.25)',
});

const QueHacemos = () => {
  return (
    <>
      <Head>
        <title>Fundmadre | ¿Como ayudar? </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderContainer>
        <Header />
      </HeaderContainer>
      <main>
        <HowToHelp />
      </main>
      <footer>
        <FooterColumns></FooterColumns>
      </footer>
    </>
  )
}

export default QueHacemos
