import { styled } from '../stitches.config';
import { Header } from '../components/Header'
import Head from 'next/head';
import { FooterColumns } from '../components/Footer';
import { MainForm } from '../components/Main/Contact';


const HeaderContainer = styled('div', {
  boxShadow: '0px 4px 4px rgba(0, 0, 0, 0.25)',
});

const QueHacemos = () => {
  return (
    <>
      <Head>
        <title>Fundmadre | Contactanos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderContainer>
        <Header />
      </HeaderContainer>
      <main>
        <MainForm />
      </main>
      <footer>
        <FooterColumns></FooterColumns>
      </footer>
    </>
  )
}
  
export default QueHacemos
