import type { NextPage } from 'next'
import Head from 'next/head'
import MainBanner from '../components/Main/Banner'
import { Header } from '../components/Header'
import { Hero } from '../components/Hero'
import banners from '../data/banners'
import { styled } from '../stitches.config'
import { FooterColumns } from '../components/Footer'
import { NavColaborate } from '../components/Main/ColaborateNav'
import { IdCardIcon } from '@radix-ui/react-icons'

// TODO: use "f1 -> Organize imports" VSCode util in all the pages

// TODO: format all document with prettier with the console

// TODO: Create a component call "PageSkeleton" with the CustomHead component (Check first JSX comment) to avoid repeat the same code all the time

// TODO: Remove dead code and use a div. here can be used just a div instead of an styled div
const HeaderContainer = styled('div', {
});

const Home: NextPage = () => {
  return (
    <>
      {/* TODO: Create a component call "CustomHead" to avoid repeat this information in every page */}
      <Head>
        <title>Fundmadre | Home</title>
        {/* TODO: Update this description and use information related to the institution */}
        <meta name="description" content="Generated by create next app" />
        {/* TODO: Update favicon and remove the existing one*/}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderContainer>
        <Header />
      </HeaderContainer>
      <main>
        <Hero />
        <MainBanner text={banners.mainPage} />
        {/* TODO: Collaborate with double l */}
        <NavColaborate sliders={IdCardIcon.arguments} />
      </main>
      <footer>
        <FooterColumns />
      </footer>
    </>
  )
}


export default Home
