import type { NextPage } from 'next'
import Head from 'next/head'
import MainBanner from '../components/Main/Banner'
import { Header } from '../components/Header'
import { Hero } from '../components/Hero'
import banners from '../data/banners'
import { styled } from '../stitches.config'
import { FooterColumns } from '../components/Footer'
import { MainForm } from '../components/Main/Contact'
import { NavColaborate } from '../components/Main/ColaborateNav'
import DropDownMenu from '../components/Main/DropDownMenu'

const HeaderContainer = styled('div', {
  variants: {
    hidden: {
      Desktop: {

      },
      Tablet: {

      },
      Mobile: {

      }
    }
  }
});

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Fundmadre</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderContainer
        hidden={{
          '@initial': 'Mobile',
          '@bp2': 'Tablet',
          '@bp3': 'Desktop'
        }}>
        <Header />
      </HeaderContainer>
      <main>
        <Hero />
        <MainBanner text={banners.mainPage} />
        <NavColaborate />
      </main>
      <footer>
        <FooterColumns />
      </footer>
    </>
  )
}

export default Home
