import type { NextPage } from 'next'
import Head from 'next/head'
import MainBanner from '../components/Main/Banner'
import { Header } from '../components/Header'
import { Hero } from '../components/Hero'
import banners from '../data/banners'
import { styled } from '../stitches.config'
import { FooterColumns } from '../components/Footer'
import { MainForm } from '../components/Main/Contact'
import { NavColaborate } from '../components/Main/ColaborateNav'
import DropDownMenu from '../components/Main/DropDownMenu'

const HeaderContainer = styled('div', {});

const HeaderContainerMobile = styled('div', {
  variants: {
    hidden: {
      Desktop: {
        paddingX: '3rem',
        paddingTop: '0.75rem',
        paddingBottom: '0.38rem',
        marginBottom: '0.37rem',
        boxShadow: '0px 4px 4px rgba(0, 0, 0, 0.25)',
      },
      Tablet: {
        paddingX: '3rem',
        paddingTop: '0.75rem',
        paddingBottom: '0.38rem',
        marginBottom: '0.37rem',
        boxShadow: '0px 4px 4px rgba(0, 0, 0, 0.25)',
      },
      Mobile: {
        paddingX: '3rem',
        paddingTop: '0.75rem',
        paddingBottom: '0.38rem',
        marginBottom: '0.37rem',
        boxShadow: '0px 4px 4px rgba(0, 0, 0, 0.25)',
      }
    }
  }
})

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Fundmadre</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderContainer>
        {/* <Header /> */}
      </HeaderContainer>
      {/* <HeaderContainerMobile
        hidden={{
          '@initial': 'Mobile',
          '@bp2': 'Tablet',
          '@bp3': 'Desktop',
        }}>
        <DropDownMenu />
      </HeaderContainerMobile> */}
      <main>
        <Hero />
        <MainBanner text={banners.mainPage} />
        <NavColaborate />
      </main>
      <footer>
        <FooterColumns />
      </footer>
    </>
  )
}

export default Home
