import { styled } from '@stitches/react';
import Head from 'next/head';
import { AbouteUs } from '../components/AboutUs'
import { Header } from '../components/Header'
import { FooterColumns } from '../components/Footer';
import { OurTeam } from '../components/OurTeam';

const HeaderContainer = styled('div', {
    boxShadow: '0px 4px 4px rgba(0, 0, 0, 0.25)',
  });

const QuienesSomos = () => {
    return (
      <>
        <Head>
          <title>Fundmadre | ¿Quiénes somos?</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <HeaderContainer>
          <Header />
        </HeaderContainer>
        <main>
            <AbouteUs/>
            {/* <OurTeam/> */}
        </main>
        <footer>
        <FooterColumns></FooterColumns>
        </footer>
      </>
    )
  }
  
  export default QuienesSomos
  